// <auto-generated />
using System;
using BusLisbon.Api.Observations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusLisbon.Api.Observations.Migrations
{
    [DbContext(typeof(ObservationsContext))]
    [Migration("20260819111635_CreateLineReliability")]
    partial class CreateLineReliability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusLisbon.Api.Observations.ArrivalObservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("EstimatedUnix")
                        .HasColumnType("bigint");

                    b.Property<string>("LineId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("ObservedUnix")
                        .HasColumnType("bigint");

                    b.Property<string>("PatternId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("ScheduledUnix")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceDate");

                    b.HasIndex("StopId", "LineId", "ScheduledUnix")
                        .IsUnique();

                    b.ToTable("Arrivals");
                });

            modelBuilder.Entity("BusLisbon.Api.Reliability.LineReliability", b =>
                {
                    b.Property<string>("LineId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<double>("AverageLatenessSeconds")
                        .HasColumnType("float");

                    b.Property<long>("ComputedAtUnix")
                        .HasColumnType("bigint");

                    b.Property<int>("Early")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FirstServiceDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("LastServiceDate")
                        .HasColumnType("date");

                    b.Property<int>("Late")
                        .HasColumnType("int");

                    b.Property<int>("Passages")
                        .HasColumnType("int");

                    b.Property<int>("WithinTolerance")
                        .HasColumnType("int");

                    b.HasKey("LineId");

                    b.ToTable("LineReliability");
                });
#pragma warning restore 612, 618
        }
    }
}
