properties:
  template:
    scale:
      minReplicas: 0
      maxReplicas: 1
      cooldownPeriod: 300
      pollingInterval: 30
      rules:
        - name: incoming-requests
          http:
            metadata:
              concurrentRequests: "10"
        - name: daytime
          custom:
            type: cron
            metadata:
              timezone: Europe/Lisbon
              start: "0 9 * * *"
              end: "0 0 * * *"
              desiredReplicas: "1"
